#!/bin/bash

intuition_user=$(whoami)

echo "Taking down the NCATS Server."
docker-compose -f docker-compose.prod.yml down -v

echo "Building back from scratch."
docker system prune

docker-compose -f docker-compose.prod.yml build

echo "Bringing up server."
docker-compose -f docker-compose.prod.yml up -d
docker-compose -f docker-compose.prod.yml exec web python3 manage.py makemigrations
docker-compose -f docker-compose.prod.yml exec web python3 manage.py migrate --noinput
docker-compose -f docker-compose.prod.yml exec web python3 manage.py collectstatic --no-input

FIXTURE_LOCATION= python -c 'from chp_data.chp_look_up.DataHandler import DataHandler
print(DataHandler.getGeneToPathwayFixture())'
docker-compose -f docker-compose.stage.yaml exec web python3 manage.py loaddata FIXTURE_LOCATION

echo "Server should now be up."

echo "Check logs with: docker-compose -f docker-compose.prod.yml logs -f"
