#!/bin/bash

intuition_user=$(whoami)

echo "Taking down the NCATS Server."
docker-compose -f docker-compose.stage.yml down -v

echo "Building back from scratch."
docker system prune

docker-compose -f docker-compose.stage.yml build
echo "Bringing up server."
docker-compose -f docker-compose.stage.yml up -d
docker-compose -f docker-compose.stage.yml exec web python3 manage.py makemigrations
docker-compose -f docker-compose.stage.yml exec web python3 manage.py migrate --noinput
docker-compose -f docker-compose.stage.yml exec web python3 manage.py collectstatic --no-input --clear

FIXTURE_LOCATION= docker-compose -f docker-compose.stage.yml exec web python3 -c 'from chp_data.LookUpDataHandler import DataHandler
print(DataHandler.getGeneToPathwayFixture())'
docker-compose -f docker-compose.stage.yaml exec web python3 manage.py loaddata FIXTURE_LOCATION

echo "Server should now be up."

echo "Check logs with: docker-compose -f docker-compose.stage.yml logs -f"
