#!/bin/bash

intuition_user=$(whoami)

echo "Taking down the NCATS Server."
docker-compose -f docker-compose.jenkins.yml down -v

echo "Building back from scratch."
docker system prune

docker-compose -f docker-compose.prod.yml build

echo "Bringing up server."
docker-compose -f docker-compose.prod.yml up -d
docker-compose -f docker-compose.prod.yml exec web python3 manage.py makemigrations
docker-compose -f docker-compose.prod.yml exec web python3 manage.py migrate --noinput
docker-compose -f docker-compose.prod.yml exec web python3 manage.py collectstatic --no-input
echo "Server should now be up."

echo "Check logs with: docker-compose -f docker-compose.prod.yml logs -f"
