#!/bin/bash

intuition_user=$(whoami)

echo "Taking down the NCATS Server."
docker-compose -f docker-compose.stage.yml down -v

echo "Building back from scratch."
docker system prune

docker-compose -f docker-compose.stage.yml build --progress=plain
echo "Bringing up server."
docker-compose -f docker-compose.stage.yml up -d
docker-compose -f docker-compose.stage.yml exec web python3 manage.py makemigrations
docker-compose -f docker-compose.stage.yml exec web python3 manage.py migrate --noinput
docker-compose -f docker-compose.stage.yml exec web python3 manage.py collectstatic --no-input --clear

docker-compose -f docker-compose.stage.yml exec web python3 manage.py loaddata /usr/local/lib/python3.8/dist-packages/data/chp_look_up_data/geneToPathway.json


echo "Server should now be up."

echo "Check logs with: docker-compose -f docker-compose.stage.yml logs -f"
