#!/bin/bash

# Variables
django_superuser_username='cat secrets/chp_api/django_superuser_username.txt'
django_superuser_email='cat secrets/chp_api/django_superuser_email.txt'

# Only to be run when building on dev machine
# use --no-cache if need to rebuild submodules
docker compose build --no-cache

docker compose up -d

docker compose run chp-api python3 manage.py migrate

# Create a database superuser
docker compose run --user root chp-api python3 manage.py createsuperuser --no-input #--username $django_superuser_username --email $django_superuser_email

# Load apps
docker compose run chp-api python3 manage.py runscript load_db_apps
docker compose run chp-api python3 manage.py runscript templater
docker compose run chp_api Python3 manage.py runscript gene_spec_curie_templater

docker compose run --user root chp-api python3 manage.py collectstatic --noinput

echo "Check logs with: docker compose logs -f"
