# Generated by Django 3.1.3 on 2020-12-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chp_handler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='therapuetic',
            new_name='therapeutic',
        ),
    ]
