# Generated by Django 4.2.1 on 2023-05-30 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gennifer', '0003_remove_algorithm_run_url_algorithm_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferencestudy',
            name='algorithm',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='edge_weight_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='edge_weight_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='AlgorithmInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyperparameters', models.JSONField(null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='gennifer.algorithm')),
            ],
        ),
        migrations.AddField(
            model_name='inferencestudy',
            name='algorithm_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='gennifer.algorithminstance'),
            preserve_default=False,
        ),
    ]
