# Generated by Django 4.2.1 on 2023-05-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gennifer', '0004_remove_inferencestudy_algorithm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='chp_preferred_curie',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
