# Generated by Django 4.2.3 on 2023-07-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gennifer', '0009_task_user_study_user_result_target_result_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hyperparameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('int', 'Integer'), ('bool', 'Boolean'), ('str', 'String'), ('float', 'Float')], default='float', max_length=5)),
                ('info', models.TextField(blank=True, null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperparameters', to='gennifer.algorithm')),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='avg_study_edge_weight',
            new_name='avg_task_edge_weight',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='max_study_edge_weight',
            new_name='max_task_edge_weight',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='min_study_edge_weight',
            new_name='min_task_edge_weight',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='std_study_edge_weight',
            new_name='std_task_edge_weight',
        ),
        migrations.RemoveField(
            model_name='algorithminstance',
            name='hyperparameters',
        ),
        migrations.CreateModel(
            name='HyperparameterInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(max_length=128)),
                ('algorithm_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperparameters', to='gennifer.algorithminstance')),
                ('hyperparameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='gennifer.hyperparameter')),
            ],
        ),
    ]
