pipeline {
    options {
        timestamps()
        disableConcurrentBuilds()
    }
    agent {
        node { label 'translator && aws && build && chp' }
    }
    parameters {
        string(name: 'BUILD_VERSION', defaultValue: '', description: 'The build version to deploy (optional)')
        string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS Region to deploy')
        string(name: 'KUBERNETES_CLUSTER_NAME', defaultValue: 'translator-eks-ci-blue-cluster', description: 'AWS EKS that will host this application')
    }
    triggers {
        pollSCM('H/5 * * * *')
    }
    environment {
        DOCKER_REPO_NAME = "853771734544.dkr.ecr.us-east-1.amazonaws.com/translator-ea-chp-api"
    }
    stages {
        stage('Build Version'){
            when { expression { return !params.BUILD_VERSION } }
            steps{
                script {
                    BUILD_VERSION_GENERATED = VersionNumber(
                        versionNumberString: 'v${BUILD_YEAR, XX}.${BUILD_MONTH, XX}${BUILD_DAY, XX}.${BUILDS_TODAY}',
                        projectStartDate:    '1970-01-01',
                        skipFailedBuilds:    true)
                    currentBuild.displayName = BUILD_VERSION_GENERATED
                    env.BUILD_VERSION = BUILD_VERSION_GENERATED
                    env.BUILD = 'true'
                }
            }
        }
        stage('Build Docker') {
           when { expression { return env.BUILD == 'true' }}
            steps {
                script {
                    docker.build(env.DOCKER_REPO_NAME, "--no-cache -f ./chp_api/Dockerfile ./")
                    sh 'docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 853771734544.dkr.ecr.us-east-1.amazonaws.com'
                    docker.image(env.DOCKER_REPO_NAME).push("${BUILD_VERSION}")
                    sh 'cp deploy/chp-api/configs/nginx.conf deploy/chp-api/nginx/'
                    docker.build(env.DOCKER_REPO_NAME, "--no-cache ./deploy/chp-api/nginx")
                    docker.image(env.DOCKER_REPO_NAME).push("${BUILD_VERSION}-nginx")
                    sh '''
                        docker pull halverneus/static-file-server:latest
                        docker tag halverneus/static-file-server:latest $DOCKER_REPO_NAME
                    '''
                    docker.image(env.DOCKER_REPO_NAME).push("${BUILD_VERSION}-staticfs")
                }
            }
        }
        stage('Deploy to AWS EKS') {
            agent { label 'translator && ci && deploy'}
            steps {
                configFileProvider([
                    configFile(fileId: 'values-ci.yaml', targetLocation: 'deploy/chp-api/values-ncats.yaml'),
                    configFile(fileId: 'prepare.sh', targetLocation: 'deploy/chp-api/prepare.sh')
                ]){
                    script {
                      sh '''#!/bin/bash
                      aws --region ${AWS_REGION} eks update-kubeconfig --name ${KUBERNETES_CLUSTER_NAME}
                      cd deploy/chp-api 
                      source prepare.sh 
                      /bin/bash deploy.sh
                      '''
                    }
                }
            }
            post {
                always {
                    echo " Clean up the workspace in deploy node!"
                    cleanWs()
                }
            }
        }
    }
}
