# Generated by Django 4.0.3 on 2022-03-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='chp_client_version',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='chp_data_version',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='chp_utils_version',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='chp_version',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='pybkb_version',
        ),
        migrations.AddField(
            model_name='transaction',
            name='versions',
            field=models.JSONField(default=dict),
        ),
    ]
