# Generated by Django 4.0.3 on 2022-03-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0002_remove_transaction_chp_client_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='chp_app',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
