# Generated by Django 4.2 on 2023-04-18 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0003_transaction_chp_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('curies_file', models.FileField(blank=True, null=True, upload_to='curies_files/')),
                ('meta_knowledge_graph_file', models.FileField(blank=True, null=True, upload_to='meta_knowledge_graph_files')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='chp_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatcher.app'),
        ),
    ]
