# Generated by Django 4.2 on 2023-05-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0005_zenodofile_remove_app_curies_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trapi_version', models.CharField(default='1.4', max_length=28)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
