# Generated by Django 4.2.1 on 2023-05-25 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0006_dispatchersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('object', models.CharField(max_length=128)),
                ('predicate', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('object', models.CharField(max_length=128)),
                ('predicate', models.CharField(max_length=128)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.template')),
            ],
        ),
    ]
